"""
Project-wide constants for callback data and FSM states.
"""

# Menu callback keys
MENU_ADD = "MENU_ADD"
MENU_RECENT = "MENU_RECENT"
MENU_SUM10 = "MENU_SUM10"
MENU_REPORT = "MENU_REPORT"
MENU_HELP = "MENU_HELP"
MENU_EXPORT_CSV = "MENU_EXPORT_CSV"

# FSM states
STATE_IDLE = "IDLE"
STATE_ASK_CATEGORY = "ASK_CATEGORY"
STATE_ASK_STORE = "ASK_STORE"
STATE_ASK_AMOUNT = "ASK_AMOUNT"
STATE_ASK_NOTE = "ASK_NOTE"
STATE_CONFIRM = "CONFIRM"
